---
language: php

php:
  - "5.4"
  - "5.5"
  - "5.6"
  - "7.0"
  - "7.1"
  - nightly

cache:
  directories: $HOME/.composer/cache/files

install: travis_retry composer install --prefer-dist

script: vendor/bin/phpunit
